#!/usr/bin/env ruby
require_relative "board"
require_relative "display"
require_relative "console"
require_relative "game"
require_relative "message"

game = Game.new(Display.new(Message.new), Board.new(9))
game.play
