#!/usr/bin/env ruby
require_relative "board"
require_relative "display"
require_relative "console"
require_relative "game"
require_relative "message"
require_relative "player"
require_relative "human_player"
require_relative "computer_player"
require_relative "peg"
require_relative "game_factory"
require_relative "player_factory"
require_relative "game_mode"
require_relative "session"

board = Board.new(3)
display = Display.new(Message.new)
game_factory = GameFactory.new(PlayerFactory.new, GameMode.new(display), display, board)
session = Session.new(game_factory, display)
session.start
